### PR TITLE
Update sensor comms

### PR DESCRIPTION
**Pull request by lalalandrus**
I have optimised the code and rewrote the sending and receiving frames. I realise the changes might break the YST boards but this pull request will start the conversation to see what is missed if anything.

### CODE REVIEW

**Comment by btsimonh** [comment]
only question will be the c == 0x100 vs c & 0x100.....
and the position of 0x1xx - will think about it later :)

**Comment by lalalandrus** [comment]
See http://drewspewsmuse.blogspot.com/2016/06/how-i-hacked-self-balancing-scooter.html?m=1

0x100 is the sof. And plus you didn't store the logical and so == and & would evaluate the same if the byte is always x100 but there is potential for the & to misidentify

**Comment by btsimonh** [comment]
my worry was; was it just the bit that was used, or was there a possibility of the word having data?
The whole point of 9 bit is that the 9th bit is not actual data, but instead a marker.

**Comment by lalalandrus** [comment]
As per the linked article I don't think there is data and the way you did the memcopy I don't think you used any of it before. I agree the 9th but is just a marker so they don't get collisions when the angle data has 255 in it.

**Comment by btsimonh** [comment]
see https://github.com/bipropellant/hoverboard-firmware/pull/15 which merges this....  and makes it work again on my HB :)

**Pull request closed without merging**
