### PR TITLE
Add calibration to button function

### PR DESCRIPTION
**Pull request by lalalandrus**
Power on hold power button = reserve mode for future
Power on then hold power button = save level center to EEPROM

### CODE REVIEW

**Comment by btsimonh** [comment]
like travis already :).

**Comment by lalalandrus** [comment]
Yea I usually don't check in non compilign code but I was uploading with my phone...

**Comment by lalalandrus** [comment]
Don't know if you got a notification but the code is fixed and compiles now.

**Comment by btsimonh** [comment]
tested up ok, but could not help be tinker! see PR against yours.

**Comment by lalalandrus** [comment]
@btsimonh  your PR checked to be working.

**Comment by btsimonh** [comment]
like the way the calibration works, and the way the HB works with it :).

**Pull request merged**
