### PR TITLE
Maintime

### PR DESCRIPTION
**Pull request by btsimonh**
makes main loop operate at pretty close to 5000us every time....
instruments timing.
(but on top of combined branch)

there is a commit in hbprotocol which allows some stats to be read via ascii protocol.

### CODE REVIEW

**Comment by p-h-a-i-l** [comment]
had to rebase to remove all the old commits which were already merged. Backup at maintime_bu branch

**Comment by p-h-a-i-l** [comment]
and tested protocol on usart2

**Comment by btsimonh** [comment]
@p-h-a-i-l - are you happy with the time changes?  if so, I'll work to resolve the (new) conflicts.....

**Comment by p-h-a-i-l** [comment]
Yes, looking good. We should just group the code into functions at some time.
But maybe not now, too much Ideas and new features to do housekeeping ;)

**Comment by btsimonh** [comment]
> We should just group the code into functions
last push on main breaks out power button functionality - it's a start :).
Pity it also broke this PR; will try to fix it, or make a new rebased one....

**Comment by btsimonh** [comment]
closed, please check master is ok for you :)

**Pull request merged**
