### PR TITLE
Update to fix flash and other related bugs

### PR DESCRIPTION
**Pull request by lalalandrus**
As per issue 10 comments

### CODE REVIEW

**Comment by p-h-a-i-l** [comment]
see https://github.com/bipropellant/hoverboard-firmware/issues/10

**Comment by btsimonh** [comment]
looks good to me without building and testing.
Qs:
1/ does myFlashSection (RESERVED_FLASH) exist in the flashable image? (we don't really want it to...)
2/ would it be better to, instead of 
`volatile uint8_t *flash_data = (uint8_t *) 0x08000000 + 0x40000 - 0x800;`
use .myFlashSection -
or would this force it to be inside the flashable image?

**Comment by lalalandrus** [comment]
1) the way the ld is set so that there is that I will exist in the flash image if this is undesirable i thibk can remove keep from the mysection in the linker script and include flasharea.c through a define only if you want to format the flash. 

2) you can use any region you want. We should have both the linker and flash access use the same defines. If you use a region in the middle I don't see any benefit at the moment as it reserves a chunk in the middle of the flash which could cause future issues. You can grow sections from either side and work towards the middle this way. Tail end for storage and head end for code space.

**Comment by btsimonh** [comment]
yep, see if you can remove it from the flash image.  The flash *should* initialise if the magic is not valid, but I moved from an area inside the flash image to one outside to try to keep existing flash values through firmware updates.  We can scrap 'flasharea.c' completely - I don't see it as relevant any more?

**Comment by lalalandrus** [comment]
You could change #if def Flash_storage to soemthinglike flash_init and keep the file for formatting the flash. Don't know if anyone sees value in this.

**Comment by btsimonh** [comment]
you can always init the flash via serial.... (if it does not detect that it needs to init because magic is wrong)?

**Comment by lalalandrus** [comment]
yes i just confimred it works. remove flashaccess.c and remove the keep before the .mysections

**Comment by btsimonh** [comment]
great - add the commit, and i'll see if i can test tonight.

**Comment by btsimonh** [comment]
haha...  built 'env hoverboard'; did not notice the firmware.bin was 256k, ran my flash.sh, and it failed.
Now I'll have to hold my power button until the Rpizero has booted, and operate all the logging in and flashing with the other hand!  serves me right for not being vigilent....

**Comment by lalalandrus** [comment]
Make sure you change the ld file too.  I tried my St link so we both had some setbacks.

**Comment by btsimonh** [comment]
just flashed back to @p-h-a-i-l 's 'size'  stuff and it's back. will try build again.

**Comment by btsimonh** [comment]
are you building the hoverboard env in pio?

**Comment by btsimonh** [comment]
ahh... did you not push the remove of keep?

**Comment by lalalandrus** [comment]
Miscommunication I thought you would add that commit

**Comment by lalalandrus** [comment]
oh i think it worked, if not the code is commited to my fork

**Comment by btsimonh** [comment]
ok, can confirm hoverboard operation with this combined with @p-h-a-i-l 's latest.
Now need to check protocol.

**Pull request merged**
